# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JN4uAKykeV9OVF1-EW5cK5u3EojyB3H4
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
img=cv2.imread("/content/Mountain2.jpg")

alpha = 1.5
beta = 6
adjusted = cv2.convertScaleAbs(img, alpha=alpha, beta=beta)
cv2_imshow(img)
cv2_imshow(adjusted)